/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables;


import com.insightaction.db.Insightaction;
import com.insightaction.db.Keys;
import com.insightaction.db.tables.records.VendorRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vendor extends TableImpl<VendorRecord> {

	private static final long serialVersionUID = -1585969986;

	/**
	 * The reference instance of <code>insightaction.VENDOR</code>
	 */
	public static final Vendor VENDOR = new Vendor();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VendorRecord> getRecordType() {
		return VendorRecord.class;
	}

	/**
	 * The column <code>insightaction.VENDOR.id</code>.
	 */
	public final TableField<VendorRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>insightaction.VENDOR.createDate</code>.
	 */
	public final TableField<VendorRecord, Timestamp> CREATEDATE = createField("createDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>insightaction.VENDOR.modifiedDate</code>.
	 */
	public final TableField<VendorRecord, Timestamp> MODIFIEDDATE = createField("modifiedDate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>insightaction.VENDOR.vendor</code>.
	 */
	public final TableField<VendorRecord, String> VENDOR_ = createField("vendor", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>insightaction.VENDOR.vendorNumber</code>.
	 */
	public final TableField<VendorRecord, String> VENDORNUMBER = createField("vendorNumber", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>insightaction.VENDOR</code> table reference
	 */
	public Vendor() {
		this("VENDOR", null);
	}

	/**
	 * Create an aliased <code>insightaction.VENDOR</code> table reference
	 */
	public Vendor(String alias) {
		this(alias, VENDOR);
	}

	private Vendor(String alias, Table<VendorRecord> aliased) {
		this(alias, aliased, null);
	}

	private Vendor(String alias, Table<VendorRecord> aliased, Field<?>[] parameters) {
		super(alias, Insightaction.INSIGHTACTION, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<VendorRecord, Integer> getIdentity() {
		return Keys.IDENTITY_VENDOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<VendorRecord> getPrimaryKey() {
		return Keys.KEY_VENDOR_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<VendorRecord>> getKeys() {
		return Arrays.<UniqueKey<VendorRecord>>asList(Keys.KEY_VENDOR_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Vendor as(String alias) {
		return new Vendor(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Vendor rename(String name) {
		return new Vendor(name, null);
	}
}
