/**
 * This class is generated by jOOQ
 */
package com.insightaction.db;


import com.insightaction.db.tables.CsvImport;
import com.insightaction.db.tables.Product;
import com.insightaction.db.tables.ProductClassType;
import com.insightaction.db.tables.Store;
import com.insightaction.db.tables.StoreDataView;
import com.insightaction.db.tables.StoreProductData;
import com.insightaction.db.tables.Vendor;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Insightaction extends SchemaImpl {

	private static final long serialVersionUID = 818790010;

	/**
	 * The reference instance of <code>insightaction</code>
	 */
	public static final Insightaction INSIGHTACTION = new Insightaction();

	/**
	 * No further instances allowed
	 */
	private Insightaction() {
		super("insightaction");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			CsvImport.CSV_IMPORT,
			Product.PRODUCT,
			ProductClassType.PRODUCT_CLASS_TYPE,
			Store.STORE,
			StoreDataView.STORE_DATA_VIEW,
			StoreProductData.STORE_PRODUCT_DATA,
			Vendor.VENDOR);
	}
}
