/**
 * This class is generated by jOOQ
 */
package com.insightaction.db;


import com.insightaction.db.tables.CsvImport;
import com.insightaction.db.tables.Product;
import com.insightaction.db.tables.ProductClassType;
import com.insightaction.db.tables.Store;
import com.insightaction.db.tables.StoreDataView;
import com.insightaction.db.tables.StoreProductData;
import com.insightaction.db.tables.Vendor;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in insightaction
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table insightaction.CSV_IMPORT
	 */
	public static final CsvImport CSV_IMPORT = com.insightaction.db.tables.CsvImport.CSV_IMPORT;

	/**
	 * The table insightaction.PRODUCT
	 */
	public static final Product PRODUCT = com.insightaction.db.tables.Product.PRODUCT;

	/**
	 * The table insightaction.PRODUCT_CLASS_TYPE
	 */
	public static final ProductClassType PRODUCT_CLASS_TYPE = com.insightaction.db.tables.ProductClassType.PRODUCT_CLASS_TYPE;

	/**
	 * The table insightaction.STORE
	 */
	public static final Store STORE = com.insightaction.db.tables.Store.STORE;

	/**
	 * VIEW
	 */
	public static final StoreDataView STORE_DATA_VIEW = com.insightaction.db.tables.StoreDataView.STORE_DATA_VIEW;

	/**
	 * The table insightaction.STORE_PRODUCT_DATA
	 */
	public static final StoreProductData STORE_PRODUCT_DATA = com.insightaction.db.tables.StoreProductData.STORE_PRODUCT_DATA;

	/**
	 * The table insightaction.VENDOR
	 */
	public static final Vendor VENDOR = com.insightaction.db.tables.Vendor.VENDOR;
}
