/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CsvImport implements Serializable {

	private static final long serialVersionUID = 1360039287;

	private Integer   id;
	private String    filename;
	private Timestamp importdate;
	private Timestamp processdate;
	private String    status;
	private String    a;
	private String    b;
	private String    c;
	private String    d;
	private String    e;
	private String    f;
	private String    g;
	private String    h;
	private String    i;
	private String    j;
	private String    k;
	private String    l;
	private String    m;
	private String    n;
	private String    o;
	private String    p;
	private String    q;
	private String    r;
	private String    s;
	private String    t;

	public CsvImport() {}

	public CsvImport(CsvImport value) {
		this.id = value.id;
		this.filename = value.filename;
		this.importdate = value.importdate;
		this.processdate = value.processdate;
		this.status = value.status;
		this.a = value.a;
		this.b = value.b;
		this.c = value.c;
		this.d = value.d;
		this.e = value.e;
		this.f = value.f;
		this.g = value.g;
		this.h = value.h;
		this.i = value.i;
		this.j = value.j;
		this.k = value.k;
		this.l = value.l;
		this.m = value.m;
		this.n = value.n;
		this.o = value.o;
		this.p = value.p;
		this.q = value.q;
		this.r = value.r;
		this.s = value.s;
		this.t = value.t;
	}

	public CsvImport(
		Integer   id,
		String    filename,
		Timestamp importdate,
		Timestamp processdate,
		String    status,
		String    a,
		String    b,
		String    c,
		String    d,
		String    e,
		String    f,
		String    g,
		String    h,
		String    i,
		String    j,
		String    k,
		String    l,
		String    m,
		String    n,
		String    o,
		String    p,
		String    q,
		String    r,
		String    s,
		String    t
	) {
		this.id = id;
		this.filename = filename;
		this.importdate = importdate;
		this.processdate = processdate;
		this.status = status;
		this.a = a;
		this.b = b;
		this.c = c;
		this.d = d;
		this.e = e;
		this.f = f;
		this.g = g;
		this.h = h;
		this.i = i;
		this.j = j;
		this.k = k;
		this.l = l;
		this.m = m;
		this.n = n;
		this.o = o;
		this.p = p;
		this.q = q;
		this.r = r;
		this.s = s;
		this.t = t;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Timestamp getImportdate() {
		return this.importdate;
	}

	public void setImportdate(Timestamp importdate) {
		this.importdate = importdate;
	}

	public Timestamp getProcessdate() {
		return this.processdate;
	}

	public void setProcessdate(Timestamp processdate) {
		this.processdate = processdate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getA() {
		return this.a;
	}

	public void setA(String a) {
		this.a = a;
	}

	public String getB() {
		return this.b;
	}

	public void setB(String b) {
		this.b = b;
	}

	public String getC() {
		return this.c;
	}

	public void setC(String c) {
		this.c = c;
	}

	public String getD() {
		return this.d;
	}

	public void setD(String d) {
		this.d = d;
	}

	public String getE() {
		return this.e;
	}

	public void setE(String e) {
		this.e = e;
	}

	public String getF() {
		return this.f;
	}

	public void setF(String f) {
		this.f = f;
	}

	public String getG() {
		return this.g;
	}

	public void setG(String g) {
		this.g = g;
	}

	public String getH() {
		return this.h;
	}

	public void setH(String h) {
		this.h = h;
	}

	public String getI() {
		return this.i;
	}

	public void setI(String i) {
		this.i = i;
	}

	public String getJ() {
		return this.j;
	}

	public void setJ(String j) {
		this.j = j;
	}

	public String getK() {
		return this.k;
	}

	public void setK(String k) {
		this.k = k;
	}

	public String getL() {
		return this.l;
	}

	public void setL(String l) {
		this.l = l;
	}

	public String getM() {
		return this.m;
	}

	public void setM(String m) {
		this.m = m;
	}

	public String getN() {
		return this.n;
	}

	public void setN(String n) {
		this.n = n;
	}

	public String getO() {
		return this.o;
	}

	public void setO(String o) {
		this.o = o;
	}

	public String getP() {
		return this.p;
	}

	public void setP(String p) {
		this.p = p;
	}

	public String getQ() {
		return this.q;
	}

	public void setQ(String q) {
		this.q = q;
	}

	public String getR() {
		return this.r;
	}

	public void setR(String r) {
		this.r = r;
	}

	public String getS() {
		return this.s;
	}

	public void setS(String s) {
		this.s = s;
	}

	public String getT() {
		return this.t;
	}

	public void setT(String t) {
		this.t = t;
	}
}
