/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductClassType implements Serializable {

	private static final long serialVersionUID = -703692568;

	private Integer   id;
	private Timestamp createdate;
	private Timestamp modifieddate;
	private String    classtype;
	private String    classtypename;
	private String    classtypeno;

	public ProductClassType() {}

	public ProductClassType(ProductClassType value) {
		this.id = value.id;
		this.createdate = value.createdate;
		this.modifieddate = value.modifieddate;
		this.classtype = value.classtype;
		this.classtypename = value.classtypename;
		this.classtypeno = value.classtypeno;
	}

	public ProductClassType(
		Integer   id,
		Timestamp createdate,
		Timestamp modifieddate,
		String    classtype,
		String    classtypename,
		String    classtypeno
	) {
		this.id = id;
		this.createdate = createdate;
		this.modifieddate = modifieddate;
		this.classtype = classtype;
		this.classtypename = classtypename;
		this.classtypeno = classtypeno;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Timestamp getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Timestamp createdate) {
		this.createdate = createdate;
	}

	public Timestamp getModifieddate() {
		return this.modifieddate;
	}

	public void setModifieddate(Timestamp modifieddate) {
		this.modifieddate = modifieddate;
	}

	public String getClasstype() {
		return this.classtype;
	}

	public void setClasstype(String classtype) {
		this.classtype = classtype;
	}

	public String getClasstypename() {
		return this.classtypename;
	}

	public void setClasstypename(String classtypename) {
		this.classtypename = classtypename;
	}

	public String getClasstypeno() {
		return this.classtypeno;
	}

	public void setClasstypeno(String classtypeno) {
		this.classtypeno = classtypeno;
	}
}
