/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product implements Serializable {

	private static final long serialVersionUID = 367174053;

	private Integer   id;
	private Timestamp createdate;
	private Timestamp modifieddate;
	private String    productname;
	private String    classid;
	private Integer   productClassTypeId;
	private Integer   vendorId;
	private String    commoncode;
	private String    beveragetype;
	private String    size;
	private String    brand;
	private String    commoncodename;
	private String    commoncodeno;
	private String    listedNonlisted;
	private String    packsize;
	private String    packsizeind;
	private String    bottles;

	public Product() {}

	public Product(Product value) {
		this.id = value.id;
		this.createdate = value.createdate;
		this.modifieddate = value.modifieddate;
		this.productname = value.productname;
		this.classid = value.classid;
		this.productClassTypeId = value.productClassTypeId;
		this.vendorId = value.vendorId;
		this.commoncode = value.commoncode;
		this.beveragetype = value.beveragetype;
		this.size = value.size;
		this.brand = value.brand;
		this.commoncodename = value.commoncodename;
		this.commoncodeno = value.commoncodeno;
		this.listedNonlisted = value.listedNonlisted;
		this.packsize = value.packsize;
		this.packsizeind = value.packsizeind;
		this.bottles = value.bottles;
	}

	public Product(
		Integer   id,
		Timestamp createdate,
		Timestamp modifieddate,
		String    productname,
		String    classid,
		Integer   productClassTypeId,
		Integer   vendorId,
		String    commoncode,
		String    beveragetype,
		String    size,
		String    brand,
		String    commoncodename,
		String    commoncodeno,
		String    listedNonlisted,
		String    packsize,
		String    packsizeind,
		String    bottles
	) {
		this.id = id;
		this.createdate = createdate;
		this.modifieddate = modifieddate;
		this.productname = productname;
		this.classid = classid;
		this.productClassTypeId = productClassTypeId;
		this.vendorId = vendorId;
		this.commoncode = commoncode;
		this.beveragetype = beveragetype;
		this.size = size;
		this.brand = brand;
		this.commoncodename = commoncodename;
		this.commoncodeno = commoncodeno;
		this.listedNonlisted = listedNonlisted;
		this.packsize = packsize;
		this.packsizeind = packsizeind;
		this.bottles = bottles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Timestamp getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Timestamp createdate) {
		this.createdate = createdate;
	}

	public Timestamp getModifieddate() {
		return this.modifieddate;
	}

	public void setModifieddate(Timestamp modifieddate) {
		this.modifieddate = modifieddate;
	}

	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public String getClassid() {
		return this.classid;
	}

	public void setClassid(String classid) {
		this.classid = classid;
	}

	public Integer getProductClassTypeId() {
		return this.productClassTypeId;
	}

	public void setProductClassTypeId(Integer productClassTypeId) {
		this.productClassTypeId = productClassTypeId;
	}

	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	public String getCommoncode() {
		return this.commoncode;
	}

	public void setCommoncode(String commoncode) {
		this.commoncode = commoncode;
	}

	public String getBeveragetype() {
		return this.beveragetype;
	}

	public void setBeveragetype(String beveragetype) {
		this.beveragetype = beveragetype;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getCommoncodename() {
		return this.commoncodename;
	}

	public void setCommoncodename(String commoncodename) {
		this.commoncodename = commoncodename;
	}

	public String getCommoncodeno() {
		return this.commoncodeno;
	}

	public void setCommoncodeno(String commoncodeno) {
		this.commoncodeno = commoncodeno;
	}

	public String getListedNonlisted() {
		return this.listedNonlisted;
	}

	public void setListedNonlisted(String listedNonlisted) {
		this.listedNonlisted = listedNonlisted;
	}

	public String getPacksize() {
		return this.packsize;
	}

	public void setPacksize(String packsize) {
		this.packsize = packsize;
	}

	public String getPacksizeind() {
		return this.packsizeind;
	}

	public void setPacksizeind(String packsizeind) {
		this.packsizeind = packsizeind;
	}

	public String getBottles() {
		return this.bottles;
	}

	public void setBottles(String bottles) {
		this.bottles = bottles;
	}
}
