/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Store implements Serializable {

	private static final long serialVersionUID = 761224484;

	private Integer   id;
	private Timestamp createdate;
	private Timestamp modifieddate;
	private String    storelicenseename;
	private String    state;
	private String    storelicenseeind;
	private String    zip;
	private String    storelicenseeno;
	private String    address1;
	private String    city;

	public Store() {}

	public Store(Store value) {
		this.id = value.id;
		this.createdate = value.createdate;
		this.modifieddate = value.modifieddate;
		this.storelicenseename = value.storelicenseename;
		this.state = value.state;
		this.storelicenseeind = value.storelicenseeind;
		this.zip = value.zip;
		this.storelicenseeno = value.storelicenseeno;
		this.address1 = value.address1;
		this.city = value.city;
	}

	public Store(
		Integer   id,
		Timestamp createdate,
		Timestamp modifieddate,
		String    storelicenseename,
		String    state,
		String    storelicenseeind,
		String    zip,
		String    storelicenseeno,
		String    address1,
		String    city
	) {
		this.id = id;
		this.createdate = createdate;
		this.modifieddate = modifieddate;
		this.storelicenseename = storelicenseename;
		this.state = state;
		this.storelicenseeind = storelicenseeind;
		this.zip = zip;
		this.storelicenseeno = storelicenseeno;
		this.address1 = address1;
		this.city = city;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Timestamp getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Timestamp createdate) {
		this.createdate = createdate;
	}

	public Timestamp getModifieddate() {
		return this.modifieddate;
	}

	public void setModifieddate(Timestamp modifieddate) {
		this.modifieddate = modifieddate;
	}

	public String getStorelicenseename() {
		return this.storelicenseename;
	}

	public void setStorelicenseename(String storelicenseename) {
		this.storelicenseename = storelicenseename;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getStorelicenseeind() {
		return this.storelicenseeind;
	}

	public void setStorelicenseeind(String storelicenseeind) {
		this.storelicenseeind = storelicenseeind;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getStorelicenseeno() {
		return this.storelicenseeno;
	}

	public void setStorelicenseeno(String storelicenseeno) {
		this.storelicenseeno = storelicenseeno;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}
}
