/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables.records;


import com.insightaction.db.tables.CsvImport;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CsvImportRecord extends UpdatableRecordImpl<CsvImportRecord> {

	private static final long serialVersionUID = 765689069;

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.filename</code>.
	 */
	public void setFilename(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.filename</code>.
	 */
	public String getFilename() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.importDate</code>.
	 */
	public void setImportdate(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.importDate</code>.
	 */
	public Timestamp getImportdate() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.processDate</code>.
	 */
	public void setProcessdate(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.processDate</code>.
	 */
	public Timestamp getProcessdate() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.status</code>.
	 */
	public void setStatus(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.status</code>.
	 */
	public String getStatus() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.A</code>.
	 */
	public void setA(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.A</code>.
	 */
	public String getA() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.B</code>.
	 */
	public void setB(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.B</code>.
	 */
	public String getB() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.C</code>.
	 */
	public void setC(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.C</code>.
	 */
	public String getC() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.D</code>.
	 */
	public void setD(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.D</code>.
	 */
	public String getD() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.E</code>.
	 */
	public void setE(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.E</code>.
	 */
	public String getE() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.F</code>.
	 */
	public void setF(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.F</code>.
	 */
	public String getF() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.G</code>.
	 */
	public void setG(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.G</code>.
	 */
	public String getG() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.H</code>.
	 */
	public void setH(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.H</code>.
	 */
	public String getH() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.I</code>.
	 */
	public void setI(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.I</code>.
	 */
	public String getI() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.J</code>.
	 */
	public void setJ(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.J</code>.
	 */
	public String getJ() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.K</code>.
	 */
	public void setK(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.K</code>.
	 */
	public String getK() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.L</code>.
	 */
	public void setL(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.L</code>.
	 */
	public String getL() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.M</code>.
	 */
	public void setM(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.M</code>.
	 */
	public String getM() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.N</code>.
	 */
	public void setN(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.N</code>.
	 */
	public String getN() {
		return (String) getValue(18);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.O</code>.
	 */
	public void setO(String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.O</code>.
	 */
	public String getO() {
		return (String) getValue(19);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.P</code>.
	 */
	public void setP(String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.P</code>.
	 */
	public String getP() {
		return (String) getValue(20);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.Q</code>.
	 */
	public void setQ(String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.Q</code>.
	 */
	public String getQ() {
		return (String) getValue(21);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.R</code>.
	 */
	public void setR(String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.R</code>.
	 */
	public String getR() {
		return (String) getValue(22);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.S</code>.
	 */
	public void setS(String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.S</code>.
	 */
	public String getS() {
		return (String) getValue(23);
	}

	/**
	 * Setter for <code>insightaction.CSV_IMPORT.T</code>.
	 */
	public void setT(String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>insightaction.CSV_IMPORT.T</code>.
	 */
	public String getT() {
		return (String) getValue(24);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CsvImportRecord
	 */
	public CsvImportRecord() {
		super(CsvImport.CSV_IMPORT);
	}

	/**
	 * Create a detached, initialised CsvImportRecord
	 */
	public CsvImportRecord(Integer id, String filename, Timestamp importdate, Timestamp processdate, String status, String a, String b, String c, String d, String e, String f, String g, String h, String i, String j, String k, String l, String m, String n, String o, String p, String q, String r, String s, String t) {
		super(CsvImport.CSV_IMPORT);

		setValue(0, id);
		setValue(1, filename);
		setValue(2, importdate);
		setValue(3, processdate);
		setValue(4, status);
		setValue(5, a);
		setValue(6, b);
		setValue(7, c);
		setValue(8, d);
		setValue(9, e);
		setValue(10, f);
		setValue(11, g);
		setValue(12, h);
		setValue(13, i);
		setValue(14, j);
		setValue(15, k);
		setValue(16, l);
		setValue(17, m);
		setValue(18, n);
		setValue(19, o);
		setValue(20, p);
		setValue(21, q);
		setValue(22, r);
		setValue(23, s);
		setValue(24, t);
	}
}
