/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables.records;


import com.insightaction.db.tables.Product;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record17<Integer, Timestamp, Timestamp, String, String, Integer, Integer, String, String, String, String, String, String, String, String, String, String> {

	private static final long serialVersionUID = 1199135341;

	/**
	 * Setter for <code>insightaction.PRODUCT.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.createDate</code>.
	 */
	public void setCreatedate(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.createDate</code>.
	 */
	public Timestamp getCreatedate() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.modifiedDate</code>.
	 */
	public void setModifieddate(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.modifiedDate</code>.
	 */
	public Timestamp getModifieddate() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.ProductName</code>.
	 */
	public void setProductname(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.ProductName</code>.
	 */
	public String getProductname() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.classId</code>.
	 */
	public void setClassid(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.classId</code>.
	 */
	public String getClassid() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.PRODUCT_CLASS_TYPE_ID</code>.
	 */
	public void setProductClassTypeId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.PRODUCT_CLASS_TYPE_ID</code>.
	 */
	public Integer getProductClassTypeId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.VENDOR_ID</code>.
	 */
	public void setVendorId(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.VENDOR_ID</code>.
	 */
	public Integer getVendorId() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.CommonCode</code>.
	 */
	public void setCommoncode(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.CommonCode</code>.
	 */
	public String getCommoncode() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.BeverageType</code>.
	 */
	public void setBeveragetype(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.BeverageType</code>.
	 */
	public String getBeveragetype() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.Size</code>.
	 */
	public void setSize(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.Size</code>.
	 */
	public String getSize() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.Brand</code>.
	 */
	public void setBrand(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.Brand</code>.
	 */
	public String getBrand() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.CommonCodeName</code>.
	 */
	public void setCommoncodename(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.CommonCodeName</code>.
	 */
	public String getCommoncodename() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.CommonCodeNo</code>.
	 */
	public void setCommoncodeno(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.CommonCodeNo</code>.
	 */
	public String getCommoncodeno() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.Listed_NonListed</code>.
	 */
	public void setListedNonlisted(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.Listed_NonListed</code>.
	 */
	public String getListedNonlisted() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.PackSize</code>.
	 */
	public void setPacksize(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.PackSize</code>.
	 */
	public String getPacksize() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.PackSizeInd</code>.
	 */
	public void setPacksizeind(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.PackSizeInd</code>.
	 */
	public String getPacksizeind() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT.Bottles</code>.
	 */
	public void setBottles(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT.Bottles</code>.
	 */
	public String getBottles() {
		return (String) getValue(16);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record17 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row17<Integer, Timestamp, Timestamp, String, String, Integer, Integer, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
		return (Row17) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row17<Integer, Timestamp, Timestamp, String, String, Integer, Integer, String, String, String, String, String, String, String, String, String, String> valuesRow() {
		return (Row17) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Product.PRODUCT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Product.PRODUCT.CREATEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return Product.PRODUCT.MODIFIEDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Product.PRODUCT.PRODUCTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Product.PRODUCT.CLASSID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Product.PRODUCT.PRODUCT_CLASS_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Product.PRODUCT.VENDOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Product.PRODUCT.COMMONCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Product.PRODUCT.BEVERAGETYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Product.PRODUCT.SIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Product.PRODUCT.BRAND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return Product.PRODUCT.COMMONCODENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return Product.PRODUCT.COMMONCODENO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return Product.PRODUCT.LISTED_NONLISTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field15() {
		return Product.PRODUCT.PACKSIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field16() {
		return Product.PRODUCT.PACKSIZEIND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field17() {
		return Product.PRODUCT.BOTTLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getCreatedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getModifieddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getProductname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getClassid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getProductClassTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getVendorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getCommoncode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getBeveragetype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getSize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getBrand();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getCommoncodename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getCommoncodeno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getListedNonlisted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getPacksize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value16() {
		return getPacksizeind();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value17() {
		return getBottles();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value2(Timestamp value) {
		setCreatedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value3(Timestamp value) {
		setModifieddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value4(String value) {
		setProductname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value5(String value) {
		setClassid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value6(Integer value) {
		setProductClassTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value7(Integer value) {
		setVendorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value8(String value) {
		setCommoncode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value9(String value) {
		setBeveragetype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value10(String value) {
		setSize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value11(String value) {
		setBrand(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value12(String value) {
		setCommoncodename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value13(String value) {
		setCommoncodeno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value14(String value) {
		setListedNonlisted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value15(String value) {
		setPacksize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value16(String value) {
		setPacksizeind(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord value17(String value) {
		setBottles(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductRecord values(Integer value1, Timestamp value2, Timestamp value3, String value4, String value5, Integer value6, Integer value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProductRecord
	 */
	public ProductRecord() {
		super(Product.PRODUCT);
	}

	/**
	 * Create a detached, initialised ProductRecord
	 */
	public ProductRecord(Integer id, Timestamp createdate, Timestamp modifieddate, String productname, String classid, Integer productClassTypeId, Integer vendorId, String commoncode, String beveragetype, String size, String brand, String commoncodename, String commoncodeno, String listedNonlisted, String packsize, String packsizeind, String bottles) {
		super(Product.PRODUCT);

		setValue(0, id);
		setValue(1, createdate);
		setValue(2, modifieddate);
		setValue(3, productname);
		setValue(4, classid);
		setValue(5, productClassTypeId);
		setValue(6, vendorId);
		setValue(7, commoncode);
		setValue(8, beveragetype);
		setValue(9, size);
		setValue(10, brand);
		setValue(11, commoncodename);
		setValue(12, commoncodeno);
		setValue(13, listedNonlisted);
		setValue(14, packsize);
		setValue(15, packsizeind);
		setValue(16, bottles);
	}
}
