/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables.records;


import com.insightaction.db.tables.ProductClassType;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductClassTypeRecord extends UpdatableRecordImpl<ProductClassTypeRecord> implements Record6<Integer, Timestamp, Timestamp, String, String, String> {

	private static final long serialVersionUID = 1709519337;

	/**
	 * Setter for <code>insightaction.PRODUCT_CLASS_TYPE.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT_CLASS_TYPE.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT_CLASS_TYPE.createDate</code>.
	 */
	public void setCreatedate(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT_CLASS_TYPE.createDate</code>.
	 */
	public Timestamp getCreatedate() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT_CLASS_TYPE.modifiedDate</code>.
	 */
	public void setModifieddate(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT_CLASS_TYPE.modifiedDate</code>.
	 */
	public Timestamp getModifieddate() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT_CLASS_TYPE.classType</code>.
	 */
	public void setClasstype(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT_CLASS_TYPE.classType</code>.
	 */
	public String getClasstype() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT_CLASS_TYPE.classTypeName</code>.
	 */
	public void setClasstypename(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT_CLASS_TYPE.classTypeName</code>.
	 */
	public String getClasstypename() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>insightaction.PRODUCT_CLASS_TYPE.classTypeNo</code>.
	 */
	public void setClasstypeno(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>insightaction.PRODUCT_CLASS_TYPE.classTypeNo</code>.
	 */
	public String getClasstypeno() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Timestamp, Timestamp, String, String, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Timestamp, Timestamp, String, String, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ProductClassType.PRODUCT_CLASS_TYPE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return ProductClassType.PRODUCT_CLASS_TYPE.CREATEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return ProductClassType.PRODUCT_CLASS_TYPE.MODIFIEDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return ProductClassType.PRODUCT_CLASS_TYPE.CLASSTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return ProductClassType.PRODUCT_CLASS_TYPE.CLASSTYPENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return ProductClassType.PRODUCT_CLASS_TYPE.CLASSTYPENO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getCreatedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getModifieddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getClasstype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getClasstypename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getClasstypeno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductClassTypeRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductClassTypeRecord value2(Timestamp value) {
		setCreatedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductClassTypeRecord value3(Timestamp value) {
		setModifieddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductClassTypeRecord value4(String value) {
		setClasstype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductClassTypeRecord value5(String value) {
		setClasstypename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductClassTypeRecord value6(String value) {
		setClasstypeno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductClassTypeRecord values(Integer value1, Timestamp value2, Timestamp value3, String value4, String value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProductClassTypeRecord
	 */
	public ProductClassTypeRecord() {
		super(ProductClassType.PRODUCT_CLASS_TYPE);
	}

	/**
	 * Create a detached, initialised ProductClassTypeRecord
	 */
	public ProductClassTypeRecord(Integer id, Timestamp createdate, Timestamp modifieddate, String classtype, String classtypename, String classtypeno) {
		super(ProductClassType.PRODUCT_CLASS_TYPE);

		setValue(0, id);
		setValue(1, createdate);
		setValue(2, modifieddate);
		setValue(3, classtype);
		setValue(4, classtypename);
		setValue(5, classtypeno);
	}
}
