/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables.records;


import com.insightaction.db.tables.StoreProductData;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreProductDataRecord extends UpdatableRecordImpl<StoreProductDataRecord> implements Record14<Integer, Timestamp, Timestamp, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

	private static final long serialVersionUID = -1061130732;

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.createDate</code>.
	 */
	public void setCreatedate(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.createDate</code>.
	 */
	public Timestamp getCreatedate() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.modifiedDate</code>.
	 */
	public void setModifieddate(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.modifiedDate</code>.
	 */
	public Timestamp getModifieddate() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.Year</code>.
	 */
	public void setYear(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.Year</code>.
	 */
	public Integer getYear() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.Period</code>.
	 */
	public void setPeriod(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.Period</code>.
	 */
	public Integer getPeriod() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.STORE_ID</code>.
	 */
	public void setStoreId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.STORE_ID</code>.
	 */
	public Integer getStoreId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.PRODUCT_ID</code>.
	 */
	public void setProductId(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.PRODUCT_ID</code>.
	 */
	public Integer getProductId() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.Bottles</code>.
	 */
	public void setBottles(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.Bottles</code>.
	 */
	public Integer getBottles() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.CasesActual</code>.
	 */
	public void setCasesactual(BigDecimal value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.CasesActual</code>.
	 */
	public BigDecimal getCasesactual() {
		return (BigDecimal) getValue(8);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.CasesStandard</code>.
	 */
	public void setCasesstandard(BigDecimal value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.CasesStandard</code>.
	 */
	public BigDecimal getCasesstandard() {
		return (BigDecimal) getValue(9);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.Cases9Liter</code>.
	 */
	public void setCases9liter(BigDecimal value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.Cases9Liter</code>.
	 */
	public BigDecimal getCases9liter() {
		return (BigDecimal) getValue(10);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.RetailDollarVol</code>.
	 */
	public void setRetaildollarvol(BigDecimal value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.RetailDollarVol</code>.
	 */
	public BigDecimal getRetaildollarvol() {
		return (BigDecimal) getValue(11);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.ShelfDollarVol</code>.
	 */
	public void setShelfdollarvol(BigDecimal value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.ShelfDollarVol</code>.
	 */
	public BigDecimal getShelfdollarvol() {
		return (BigDecimal) getValue(12);
	}

	/**
	 * Setter for <code>insightaction.STORE_PRODUCT_DATA.FOBDollarVol</code>.
	 */
	public void setFobdollarvol(BigDecimal value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>insightaction.STORE_PRODUCT_DATA.FOBDollarVol</code>.
	 */
	public BigDecimal getFobdollarvol() {
		return (BigDecimal) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<Integer, Timestamp, Timestamp, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
		return (Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<Integer, Timestamp, Timestamp, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
		return (Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return StoreProductData.STORE_PRODUCT_DATA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return StoreProductData.STORE_PRODUCT_DATA.CREATEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return StoreProductData.STORE_PRODUCT_DATA.MODIFIEDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return StoreProductData.STORE_PRODUCT_DATA.YEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return StoreProductData.STORE_PRODUCT_DATA.PERIOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return StoreProductData.STORE_PRODUCT_DATA.STORE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return StoreProductData.STORE_PRODUCT_DATA.PRODUCT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return StoreProductData.STORE_PRODUCT_DATA.BOTTLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field9() {
		return StoreProductData.STORE_PRODUCT_DATA.CASESACTUAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field10() {
		return StoreProductData.STORE_PRODUCT_DATA.CASESSTANDARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field11() {
		return StoreProductData.STORE_PRODUCT_DATA.CASES9LITER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field12() {
		return StoreProductData.STORE_PRODUCT_DATA.RETAILDOLLARVOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field13() {
		return StoreProductData.STORE_PRODUCT_DATA.SHELFDOLLARVOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field14() {
		return StoreProductData.STORE_PRODUCT_DATA.FOBDOLLARVOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getCreatedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getModifieddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getYear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getPeriod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getStoreId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getProductId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getBottles();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value9() {
		return getCasesactual();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value10() {
		return getCasesstandard();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value11() {
		return getCases9liter();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value12() {
		return getRetaildollarvol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value13() {
		return getShelfdollarvol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value14() {
		return getFobdollarvol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value2(Timestamp value) {
		setCreatedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value3(Timestamp value) {
		setModifieddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value4(Integer value) {
		setYear(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value5(Integer value) {
		setPeriod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value6(Integer value) {
		setStoreId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value7(Integer value) {
		setProductId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value8(Integer value) {
		setBottles(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value9(BigDecimal value) {
		setCasesactual(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value10(BigDecimal value) {
		setCasesstandard(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value11(BigDecimal value) {
		setCases9liter(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value12(BigDecimal value) {
		setRetaildollarvol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value13(BigDecimal value) {
		setShelfdollarvol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord value14(BigDecimal value) {
		setFobdollarvol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreProductDataRecord values(Integer value1, Timestamp value2, Timestamp value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, BigDecimal value9, BigDecimal value10, BigDecimal value11, BigDecimal value12, BigDecimal value13, BigDecimal value14) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StoreProductDataRecord
	 */
	public StoreProductDataRecord() {
		super(StoreProductData.STORE_PRODUCT_DATA);
	}

	/**
	 * Create a detached, initialised StoreProductDataRecord
	 */
	public StoreProductDataRecord(Integer id, Timestamp createdate, Timestamp modifieddate, Integer year, Integer period, Integer storeId, Integer productId, Integer bottles, BigDecimal casesactual, BigDecimal casesstandard, BigDecimal cases9liter, BigDecimal retaildollarvol, BigDecimal shelfdollarvol, BigDecimal fobdollarvol) {
		super(StoreProductData.STORE_PRODUCT_DATA);

		setValue(0, id);
		setValue(1, createdate);
		setValue(2, modifieddate);
		setValue(3, year);
		setValue(4, period);
		setValue(5, storeId);
		setValue(6, productId);
		setValue(7, bottles);
		setValue(8, casesactual);
		setValue(9, casesstandard);
		setValue(10, cases9liter);
		setValue(11, retaildollarvol);
		setValue(12, shelfdollarvol);
		setValue(13, fobdollarvol);
	}
}
