/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables.records;


import com.insightaction.db.tables.StoreDataView;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Row;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreDataViewRecord extends TableRecordImpl<StoreDataViewRecord> implements Record16<Integer, Timestamp, Timestamp, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, String> {

	private static final long serialVersionUID = -777790301;

	/**
	 * Setter for <code>insightaction.store_data_view.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.createDate</code>.
	 */
	public void setCreatedate(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.createDate</code>.
	 */
	public Timestamp getCreatedate() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.modifiedDate</code>.
	 */
	public void setModifieddate(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.modifiedDate</code>.
	 */
	public Timestamp getModifieddate() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.Year</code>.
	 */
	public void setYear(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.Year</code>.
	 */
	public Integer getYear() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.Period</code>.
	 */
	public void setPeriod(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.Period</code>.
	 */
	public Integer getPeriod() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.STORE_ID</code>.
	 */
	public void setStoreId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.STORE_ID</code>.
	 */
	public Integer getStoreId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.PRODUCT_ID</code>.
	 */
	public void setProductId(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.PRODUCT_ID</code>.
	 */
	public Integer getProductId() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.Bottles</code>.
	 */
	public void setBottles(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.Bottles</code>.
	 */
	public Integer getBottles() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.CasesActual</code>.
	 */
	public void setCasesactual(BigDecimal value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.CasesActual</code>.
	 */
	public BigDecimal getCasesactual() {
		return (BigDecimal) getValue(8);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.CasesStandard</code>.
	 */
	public void setCasesstandard(BigDecimal value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.CasesStandard</code>.
	 */
	public BigDecimal getCasesstandard() {
		return (BigDecimal) getValue(9);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.Cases9Liter</code>.
	 */
	public void setCases9liter(BigDecimal value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.Cases9Liter</code>.
	 */
	public BigDecimal getCases9liter() {
		return (BigDecimal) getValue(10);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.RetailDollarVol</code>.
	 */
	public void setRetaildollarvol(BigDecimal value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.RetailDollarVol</code>.
	 */
	public BigDecimal getRetaildollarvol() {
		return (BigDecimal) getValue(11);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.ShelfDollarVol</code>.
	 */
	public void setShelfdollarvol(BigDecimal value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.ShelfDollarVol</code>.
	 */
	public BigDecimal getShelfdollarvol() {
		return (BigDecimal) getValue(12);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.FOBDollarVol</code>.
	 */
	public void setFobdollarvol(BigDecimal value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.FOBDollarVol</code>.
	 */
	public BigDecimal getFobdollarvol() {
		return (BigDecimal) getValue(13);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.storeLicenseeName</code>.
	 */
	public void setStorelicenseename(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.storeLicenseeName</code>.
	 */
	public String getStorelicenseename() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>insightaction.store_data_view.ProductName</code>.
	 */
	public void setProductname(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>insightaction.store_data_view.ProductName</code>.
	 */
	public String getProductname() {
		return (String) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<Integer, Timestamp, Timestamp, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, String> fieldsRow() {
		return (Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<Integer, Timestamp, Timestamp, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, String> valuesRow() {
		return (Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return StoreDataView.STORE_DATA_VIEW.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return StoreDataView.STORE_DATA_VIEW.CREATEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return StoreDataView.STORE_DATA_VIEW.MODIFIEDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return StoreDataView.STORE_DATA_VIEW.YEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return StoreDataView.STORE_DATA_VIEW.PERIOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return StoreDataView.STORE_DATA_VIEW.STORE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return StoreDataView.STORE_DATA_VIEW.PRODUCT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return StoreDataView.STORE_DATA_VIEW.BOTTLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field9() {
		return StoreDataView.STORE_DATA_VIEW.CASESACTUAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field10() {
		return StoreDataView.STORE_DATA_VIEW.CASESSTANDARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field11() {
		return StoreDataView.STORE_DATA_VIEW.CASES9LITER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field12() {
		return StoreDataView.STORE_DATA_VIEW.RETAILDOLLARVOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field13() {
		return StoreDataView.STORE_DATA_VIEW.SHELFDOLLARVOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field14() {
		return StoreDataView.STORE_DATA_VIEW.FOBDOLLARVOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field15() {
		return StoreDataView.STORE_DATA_VIEW.STORELICENSEENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field16() {
		return StoreDataView.STORE_DATA_VIEW.PRODUCTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getCreatedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getModifieddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getYear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getPeriod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getStoreId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getProductId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getBottles();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value9() {
		return getCasesactual();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value10() {
		return getCasesstandard();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value11() {
		return getCases9liter();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value12() {
		return getRetaildollarvol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value13() {
		return getShelfdollarvol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value14() {
		return getFobdollarvol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getStorelicenseename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value16() {
		return getProductname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value2(Timestamp value) {
		setCreatedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value3(Timestamp value) {
		setModifieddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value4(Integer value) {
		setYear(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value5(Integer value) {
		setPeriod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value6(Integer value) {
		setStoreId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value7(Integer value) {
		setProductId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value8(Integer value) {
		setBottles(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value9(BigDecimal value) {
		setCasesactual(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value10(BigDecimal value) {
		setCasesstandard(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value11(BigDecimal value) {
		setCases9liter(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value12(BigDecimal value) {
		setRetaildollarvol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value13(BigDecimal value) {
		setShelfdollarvol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value14(BigDecimal value) {
		setFobdollarvol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value15(String value) {
		setStorelicenseename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord value16(String value) {
		setProductname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreDataViewRecord values(Integer value1, Timestamp value2, Timestamp value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, BigDecimal value9, BigDecimal value10, BigDecimal value11, BigDecimal value12, BigDecimal value13, BigDecimal value14, String value15, String value16) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StoreDataViewRecord
	 */
	public StoreDataViewRecord() {
		super(StoreDataView.STORE_DATA_VIEW);
	}

	/**
	 * Create a detached, initialised StoreDataViewRecord
	 */
	public StoreDataViewRecord(Integer id, Timestamp createdate, Timestamp modifieddate, Integer year, Integer period, Integer storeId, Integer productId, Integer bottles, BigDecimal casesactual, BigDecimal casesstandard, BigDecimal cases9liter, BigDecimal retaildollarvol, BigDecimal shelfdollarvol, BigDecimal fobdollarvol, String storelicenseename, String productname) {
		super(StoreDataView.STORE_DATA_VIEW);

		setValue(0, id);
		setValue(1, createdate);
		setValue(2, modifieddate);
		setValue(3, year);
		setValue(4, period);
		setValue(5, storeId);
		setValue(6, productId);
		setValue(7, bottles);
		setValue(8, casesactual);
		setValue(9, casesstandard);
		setValue(10, cases9liter);
		setValue(11, retaildollarvol);
		setValue(12, shelfdollarvol);
		setValue(13, fobdollarvol);
		setValue(14, storelicenseename);
		setValue(15, productname);
	}
}
