/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables.records;


import com.insightaction.db.tables.Store;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreRecord extends UpdatableRecordImpl<StoreRecord> implements Record10<Integer, Timestamp, Timestamp, String, String, String, String, String, String, String> {

	private static final long serialVersionUID = -1304357225;

	/**
	 * Setter for <code>insightaction.STORE.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>insightaction.STORE.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>insightaction.STORE.createDate</code>.
	 */
	public void setCreatedate(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>insightaction.STORE.createDate</code>.
	 */
	public Timestamp getCreatedate() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>insightaction.STORE.modifiedDate</code>.
	 */
	public void setModifieddate(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>insightaction.STORE.modifiedDate</code>.
	 */
	public Timestamp getModifieddate() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>insightaction.STORE.storeLicenseeName</code>.
	 */
	public void setStorelicenseename(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>insightaction.STORE.storeLicenseeName</code>.
	 */
	public String getStorelicenseename() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>insightaction.STORE.state</code>.
	 */
	public void setState(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>insightaction.STORE.state</code>.
	 */
	public String getState() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>insightaction.STORE.storeLicenseeInd</code>.
	 */
	public void setStorelicenseeind(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>insightaction.STORE.storeLicenseeInd</code>.
	 */
	public String getStorelicenseeind() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>insightaction.STORE.zip</code>.
	 */
	public void setZip(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>insightaction.STORE.zip</code>.
	 */
	public String getZip() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>insightaction.STORE.storeLicenseeNo</code>.
	 */
	public void setStorelicenseeno(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>insightaction.STORE.storeLicenseeNo</code>.
	 */
	public String getStorelicenseeno() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>insightaction.STORE.address1</code>.
	 */
	public void setAddress1(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>insightaction.STORE.address1</code>.
	 */
	public String getAddress1() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>insightaction.STORE.city</code>.
	 */
	public void setCity(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>insightaction.STORE.city</code>.
	 */
	public String getCity() {
		return (String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Timestamp, Timestamp, String, String, String, String, String, String, String> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Timestamp, Timestamp, String, String, String, String, String, String, String> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Store.STORE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Store.STORE.CREATEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return Store.STORE.MODIFIEDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Store.STORE.STORELICENSEENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Store.STORE.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Store.STORE.STORELICENSEEIND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Store.STORE.ZIP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Store.STORE.STORELICENSEENO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Store.STORE.ADDRESS1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Store.STORE.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getCreatedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getModifieddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getStorelicenseename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getStorelicenseeind();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getZip();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getStorelicenseeno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getAddress1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreRecord value2(Timestamp value) {
		setCreatedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreRecord value3(Timestamp value) {
		setModifieddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreRecord value4(String value) {
		setStorelicenseename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreRecord value5(String value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreRecord value6(String value) {
		setStorelicenseeind(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreRecord value7(String value) {
		setZip(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreRecord value8(String value) {
		setStorelicenseeno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreRecord value9(String value) {
		setAddress1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreRecord value10(String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoreRecord values(Integer value1, Timestamp value2, Timestamp value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StoreRecord
	 */
	public StoreRecord() {
		super(Store.STORE);
	}

	/**
	 * Create a detached, initialised StoreRecord
	 */
	public StoreRecord(Integer id, Timestamp createdate, Timestamp modifieddate, String storelicenseename, String state, String storelicenseeind, String zip, String storelicenseeno, String address1, String city) {
		super(Store.STORE);

		setValue(0, id);
		setValue(1, createdate);
		setValue(2, modifieddate);
		setValue(3, storelicenseename);
		setValue(4, state);
		setValue(5, storelicenseeind);
		setValue(6, zip);
		setValue(7, storelicenseeno);
		setValue(8, address1);
		setValue(9, city);
	}
}
