/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.tables.records;


import com.insightaction.db.tables.Vendor;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendorRecord extends UpdatableRecordImpl<VendorRecord> implements Record5<Integer, Timestamp, Timestamp, String, String> {

	private static final long serialVersionUID = 905251596;

	/**
	 * Setter for <code>insightaction.VENDOR.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>insightaction.VENDOR.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>insightaction.VENDOR.createDate</code>.
	 */
	public void setCreatedate(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>insightaction.VENDOR.createDate</code>.
	 */
	public Timestamp getCreatedate() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>insightaction.VENDOR.modifiedDate</code>.
	 */
	public void setModifieddate(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>insightaction.VENDOR.modifiedDate</code>.
	 */
	public Timestamp getModifieddate() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>insightaction.VENDOR.vendor</code>.
	 */
	public void setVendor(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>insightaction.VENDOR.vendor</code>.
	 */
	public String getVendor() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>insightaction.VENDOR.vendorNumber</code>.
	 */
	public void setVendornumber(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>insightaction.VENDOR.vendorNumber</code>.
	 */
	public String getVendornumber() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Timestamp, Timestamp, String, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Timestamp, Timestamp, String, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Vendor.VENDOR.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Vendor.VENDOR.CREATEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return Vendor.VENDOR.MODIFIEDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Vendor.VENDOR.VENDOR_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Vendor.VENDOR.VENDORNUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getCreatedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getModifieddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getVendor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getVendornumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendorRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendorRecord value2(Timestamp value) {
		setCreatedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendorRecord value3(Timestamp value) {
		setModifieddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendorRecord value4(String value) {
		setVendor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendorRecord value5(String value) {
		setVendornumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VendorRecord values(Integer value1, Timestamp value2, Timestamp value3, String value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VendorRecord
	 */
	public VendorRecord() {
		super(Vendor.VENDOR);
	}

	/**
	 * Create a detached, initialised VendorRecord
	 */
	public VendorRecord(Integer id, Timestamp createdate, Timestamp modifieddate, String vendor, String vendornumber) {
		super(Vendor.VENDOR);

		setValue(0, id);
		setValue(1, createdate);
		setValue(2, modifieddate);
		setValue(3, vendor);
		setValue(4, vendornumber);
	}
}
