/**
 * This class is generated by jOOQ
 */
package com.insightaction.db.routines;


import com.insightaction.db.Insightaction;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpdateShelfPrice extends AbstractRoutine<String> {

	private static final long serialVersionUID = -182253814;

	/**
	 * The parameter <code>insightaction.UPDATE_SHELF_PRICE.RETURN_VALUE</code>.
	 */
	public static final Parameter<String> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.VARCHAR.length(10), false);

	/**
	 * The parameter <code>insightaction.UPDATE_SHELF_PRICE.STORE_ID</code>.
	 */
	public static final Parameter<Integer> STORE_ID = createParameter("STORE_ID", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>insightaction.UPDATE_SHELF_PRICE.PRODUCT_ID</code>.
	 */
	public static final Parameter<Integer> PRODUCT_ID = createParameter("PRODUCT_ID", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>insightaction.UPDATE_SHELF_PRICE.PRICE</code>.
	 */
	public static final Parameter<BigDecimal> PRICE = createParameter("PRICE", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), false);

	/**
	 * Create a new routine call instance
	 */
	public UpdateShelfPrice() {
		super("UPDATE_SHELF_PRICE", Insightaction.INSIGHTACTION, org.jooq.impl.SQLDataType.VARCHAR.length(10));

		setReturnParameter(RETURN_VALUE);
		addInParameter(STORE_ID);
		addInParameter(PRODUCT_ID);
		addInParameter(PRICE);
	}

	/**
	 * Set the <code>STORE_ID</code> parameter IN value to the routine
	 */
	public void setStoreId(Integer value) {
		setValue(STORE_ID, value);
	}

	/**
	 * Set the <code>STORE_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setStoreId(Field<Integer> field) {
		setField(STORE_ID, field);
	}

	/**
	 * Set the <code>PRODUCT_ID</code> parameter IN value to the routine
	 */
	public void setProductId(Integer value) {
		setValue(PRODUCT_ID, value);
	}

	/**
	 * Set the <code>PRODUCT_ID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setProductId(Field<Integer> field) {
		setField(PRODUCT_ID, field);
	}

	/**
	 * Set the <code>PRICE</code> parameter IN value to the routine
	 */
	public void setPrice(BigDecimal value) {
		setValue(PRICE, value);
	}

	/**
	 * Set the <code>PRICE</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPrice(Field<BigDecimal> field) {
		setField(PRICE, field);
	}
}
